## SMS Spam Detection – Data Cleaning

### Objective:
To preprocess the SMS spam dataset and prepare it 
for machine learning model training.

## Importing Library and Loading Dataset

In [21]:
import pandas as pd
df = pd.read_csv("./spam.csv",encoding = "latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## Dataset Overview
Checking dataset structure and column information.

In [22]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

## Missing Value Analysis
Identifying missing values in each column.

In [23]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

## Removing Unnecessary Columns

Columns 'Unnamed: 2', 'Unnamed: 3', and 'Unnamed: 4' 

contain mostly null values and do not contribute 

to model training.

In [24]:
df = df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"] )

## Renaming Columns

Renamed columns for better readability.

v1 → Label  

v2 → Message

In [25]:
df = df.rename(columns={"v1": "Label" , "v2": "Message"} )
df

     Label                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Duplicate Check

Identified and removed duplicate messages 

to avoid data redundancy.

In [26]:
df[df.duplicated()]

     Label                                            Message
102    ham  As per your request 'Melle Melle (Oru Minnamin...
153    ham  As per your request 'Melle Melle (Oru Minnamin...
206    ham  As I entered my cabin my PA said, '' Happy B'd...
222    ham                             Sorry, I'll call later
325    ham                   No calls..messages..missed calls
...    ...                                                ...
5524  spam  You are awarded a SiPix Digital Camera! call 0...
5535   ham  I know you are thinkin malaria. But relax, chi...
5539   ham                         Just sleeping..and surfing
5553   ham                        Hahaha..use your brain dear
5558   ham                             Sorry, I'll call later

[403 rows x 2 columns]

In [27]:
df = df.drop_duplicates()

## Label Encoding

Converted categorical labels into numeric format:

ham → 0
  
spam → 1

In [28]:
df["Label"].value_counts()

Label
ham     4516
spam     653
Name: count, dtype: int64

In [29]:
df['Label'] = df['Label'].map({'ham':0, "spam" : 1})

C:\Users\anshi\AppData\Local\Temp\ipykernel_14400\1903448232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Label'] = df['Label'].map({'ham':0, "spam" : 1})

## Final Verification

Ensured no missing values and no duplicate records remain.

In [32]:
df.isnull().sum()
df.duplicated().sum()
df.shape

(5169, 2)

## Exporting Cleaned Dataset

In [31]:
df.to_csv("cleaned_SMS_spam.csv" , index = False)